import { Rancho, Raleway } from "next/font/google";
import "./global.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const rancho = Rancho({
    variable: "--font-rancho",
    subsets: ["latin"],
    weight: "400", // Rancho only has one weight (400)
});

const raleway = Raleway({
    variable: "--font-raleway",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body
                className={`${rancho.variable} ${raleway.variable} antialiased`}
            >
                <Navbar></Navbar>
                <main className="min-h-[calc(100vh-700px)]">{children}</main>
                <Footer></Footer>
            </body>
        </html>
    );
}
